name: teleprac
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  
  # Main
  flutter_native_splash: ^2.2.0+1
  get: ^4.6.5
  dartz: ^0.10.1
  # Network
  http: ^0.13.6
  html: ^0.15.4
  url_launcher: ^6.1.11
  agora_rtc_engine: ^6.2.6
  razorpay_flutter: ^1.3.5
  html_unescape: ^2.0.0
  share_plus: ^7.2.1
  cached_network_image: ^3.2.1
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  cloud_firestore: ^4.14.0
  # Local
  shared_preferences: ^2.0.15
  permission_handler: ^10.2.0
  path_provider: ^2.1.1
  # Other
  dropdown_button2: ^2.1.4
  dropdown_search: ^3.0.1 
  fluttertoast: ^8.2.4
  lottie: ^2.3.2
  geolocator: ^10.1.0
  fl_geocoder: ^0.1.0+1
  shimmer: ^3.0.0
  flutter_svg: ^2.0.5
  jiffy: ^5.0.0
  dotted_line: ^3.2.2
  path: ^1.8.2
  intl: ^0.18.1
  image_picker: ^1.0.4
  image_cropper: ^4.0.1
  flutter_pdfview: ^1.3.2
  media_scanner: ^2.1.0
  easy_signature_pad: ^1.0.6
  flutter_widget_from_html: ^0.14.11
  photo_view: ^0.14.0
  timezone: ^0.9.2
  device_info_plus: ^9.1.2
  file_picker: ^5.3.1
  pdf_compressor: ^0.2.0
  flutter_image_compress: ^2.1.0
  flutter_rating_bar: ^4.0.1
  flutter_ringtone_player: ^3.2.0
  flutter_otp_text_field: ^1.1.1
  crypto: ^3.0.3


dev_dependencies: 
  package_rename: ^1.5.3
  flutter_launcher_icons:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/main/app_icon_small.png"
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # Main
    - assets/images/main/app_icon.png
    - assets/images/main/bg_0.jpg
    - assets/images/main/bg_1.jpg
    # Onboarding Images
    - 'assets/images/onboarding/onboarding_1.jpeg'
    - 'assets/images/onboarding/onboarding_2.jpeg'
    - 'assets/images/onboarding/onboarding_3.jpeg'
    - 'assets/images/onboarding/onboarding_4.jpeg'
    - 'assets/images/onboarding/onboarding_5.jpeg'
    # Home Images
    - 'assets/images/home/home_bg.png'
    # - 'assets/images/home/diagnostic_tests.png'
    # - 'assets/images/home/online_consultation.png'
    # - 'assets/images/home/home_sample_collection.png'
    # - 'assets/images/home/online_pharmacy.png'
    - 'assets/images/home/diagnostic_tests.jpg'
    - 'assets/images/home/online_consultation.jpg'
    - 'assets/images/home/home_sample_collection.jpg'
    - 'assets/images/home/online_pharmacy.jpg'
    # Pharmacy
      # Categories
    - 'assets/images/pharmacy/categories/1.png'
    - 'assets/images/pharmacy/categories/12.png'
    - 'assets/images/pharmacy/categories/27.png'
    - 'assets/images/pharmacy/categories/28.png'
    - 'assets/images/pharmacy/categories/63.png'
      # Subcategories
    - 'assets/images/pharmacy/subcategories/8_subcat.png'
    - 'assets/images/pharmacy/subcategories/9_subcat.png'
    - 'assets/images/pharmacy/subcategories/13_subcat.png'
    - 'assets/images/pharmacy/subcategories/14_subcat.png'
    - 'assets/images/pharmacy/subcategories/15_subcat.png'
    - 'assets/images/pharmacy/subcategories/18_subcat.png'
    - 'assets/images/pharmacy/subcategories/19_subcat.png'
    - 'assets/images/pharmacy/subcategories/20_subcat.png'
    - 'assets/images/pharmacy/subcategories/21_subcat.png'
    - 'assets/images/pharmacy/subcategories/22_subcat.png'
    - 'assets/images/pharmacy/subcategories/23_subcat.png'
    - 'assets/images/pharmacy/subcategories/25_subcat.png'
    - 'assets/images/pharmacy/subcategories/26_subcat.png'
    - 'assets/images/pharmacy/subcategories/32_subcat.png'
    - 'assets/images/pharmacy/subcategories/33_subcat.png'
    - 'assets/images/pharmacy/subcategories/34_subcat.png'
    - 'assets/images/pharmacy/subcategories/36_subcat.png'
    - 'assets/images/pharmacy/subcategories/41_subcat.png'
    - 'assets/images/pharmacy/subcategories/42_subcat.png'
    - 'assets/images/pharmacy/subcategories/43_subcat.png'
    - 'assets/images/pharmacy/subcategories/44_subcat.png'
    - 'assets/images/pharmacy/subcategories/45_subcat.png'
    - 'assets/images/pharmacy/subcategories/56_subcat.png'
    - 'assets/images/pharmacy/subcategories/57_subcat.png'
    - 'assets/images/pharmacy/subcategories/58_subcat.png'
    - 'assets/images/pharmacy/subcategories/59_subcat.png'
    - 'assets/images/pharmacy/subcategories/60_subcat.png'
    - 'assets/images/pharmacy/subcategories/61_subcat.png'
    - 'assets/images/pharmacy/subcategories/62_subcat.png'
    - 'assets/images/pharmacy/subcategories/65_subcat.png'
    - 'assets/images/pharmacy/subcategories/66_subcat.png'
    # Lottie
    - assets/images/lottie/check.json
    - assets/images/lottie/loading.json
    # SVG
    - assets/images/icons/send.svg
    # Icons 
    - assets/images/icons/heart.png
    - assets/images/icons/doctor.png
    - assets/images/icons/medicine.png
    - assets/images/icons/laboratory.png
    - assets/images/icons/laboratory_1.png
    - assets/images/icons/email.png
    - assets/images/icons/mobile-app.png
    - assets/images/icons/password.png
    - assets/images/icons/admin.png
    - assets/images/icons/bell.png
    - assets/images/icons/shopping-cart.png
    - assets/images/icons/write_prescription.png
    - assets/images/icons/discount.png
    - assets/images/icons/discount_1.png
    - assets/images/icons/account.svg
    - assets/images/icons/info.png
    - assets/images/icons/education.png
    - assets/images/icons/work.png
    - assets/images/icons/check_up.png
    - assets/images/icons/clinic.png
    - assets/images/icons/online_appointment.png
    - assets/images/icons/calendar.png
    - assets/images/icons/account.png
    - assets/images/icons/flask.png
    - assets/images/icons/medicine_1.png
    - assets/images/icons/doctor_2.png
    - assets/images/icons/setting.png
    - assets/images/icons/padlock.png
    - assets/images/icons/dashboard.png
    - assets/images/icons/medical.png
    - assets/images/icons/prescription.png
    - assets/images/icons/chemical_analysis.png
    - assets/images/icons/payment.png
    - assets/images/icons/science_book.png
    - assets/images/icons/nurse.png
    - assets/images/icons/family.png
    - assets/images/icons/purchase_order.png
    - assets/images/icons/messages.png
    - assets/images/icons/invoice.png
    - assets/images/icons/positive_review.png
    - assets/images/icons/doctor_1.png
    - assets/images/icons/appointment.png


  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Cairo
      fonts:
        - asset: assets\fonts\Cairo\Cairo-Regular.ttf
        # - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
